### ISSUE TITLE
Set test name space clean up

### ISSUE THREAD

**Issue by fsadykov** [fuchicorp/main-fuchicorp#15]
Hello,

Please set a cleanup namespace test every two days. Discuss with the team how we can clean up the namespace test.
**Action**
* Create cron job on common_tools and make the job will be deployed together
* The cronjob should clean namespace test every 1 week 
* Create PR for this and make sure everyone reviews this 

https://github.com/fuchicorp/common_tools/blob/571fa2612a7a9b0e476b818433345c1457d02da5/google_k8s_namespaces.tf#L40

**Comment by hakten** [comment]
I am working on this ticket, and almost done, but I am not able to assign it to myself.
