### ISSUE TITLE
Script to pull latest tf_files

### ISSUE THREAD

**Issue by SharifAbdulcoder** [fuchicorp/main-fuchicorp#28]
Once the we are in the process of migrating into another account we need a script to pull the latest version of our tf.file for cluster_infrastructure. Your script must pull the latest tfvars file and export it $CLUSTER.TFVARS so that we may run our terraform like this : 

``` terraform apply -var-file=$CLUSTER.TFVARS ```

**Comment by fsadykov** [comment]
Created script to pull tfvars file from main fuchicorp good to go and close this ticket
