### ISSUE TITLE
Please create proper graph for FuchiCorp 

### ISSUE THREAD

**Issue by fsadykov** [fuchicorp/main-fuchicorp#32]
Hello @arginbest ,

According to our discussions would you please create proper graph for FuchiCorp. We will use your Graph for demo and also for our documentations.

Thank you

**Comment by arginbest** [comment]
Hello Farkhot please see last version v.2 and i already added to your graph page <graph-v.2, just in case send you link https://app.diagrams.net/#G1lttXHy7m7oFHxlERFJ17mMSxQ9DoH3mS

**Comment by Adnankursun** [comment]
is there any way to add the pipeline graph with the tools shown in whole process? 
![image](https://user-images.githubusercontent.com/54333199/93626941-d1a0ff80-f9a9-11ea-9ca0-b2a6286c5cdd.png)
